version: '3.4'

services:
  servicescatlog:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

  apigateway:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"


  servicerequest:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"


  adminservices:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"


  serviceprovider:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"


  notificationservices:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

